require 'open-uri'
require 'redcarpet'
require 'action_mailer'
require 'active_support/rescuable'
require 'dotenv'
require 'csv'
require 'ruby-progressbar'

require_relative 'app/mailers/rake_mailer'

namespace :download  do
  desc 'Скачивает шаблон письма'
  task :template do
    puts 'Скачиваю файл...'

    File.open('template.md', 'w') do |file|
      file.write(open('https://www.dropbox.com/s/7gzqm092ufnbha9/rake.md?dl=1').read)
    end

    puts 'Справился'
  end


  desc 'Скачивает список адресатов'
  task :recipients do
    puts 'Скачиваю файл...'

    File.open('recipients.csv', 'w') do |file|
      file.write(open('https://www.dropbox.com/s/f9bczyb623uzwee/recipients.csv?dl=1').read)
    end

    puts 'Справился'
  end
end

namespace :template do
  desc 'Конвертируем шаблон'
  task convert: ['download:template'] do
    puts 'Конвертирую файл'
    renderer = Redcarpet::Render::HTML.new
 *   markdown = Redcarpet::Markdown.new(renderer, extensions = {})
    template_markdown = File.read('template.md')

    File.open('app/views/mailers/rake_mailer/lesson_plan.html', 'w') do |file|
      file.write(markdown.render(template_markdown))
    end

    puts 'Справился'
  end
end

namespace :mailer do
  task :configure do
    Dotenv.load

    ActionMailer::Base.view_paths = File.expand_path('../app/views/mailers', __FILE__)
    ActionMailer::Base.delivery_method = :smtp
    ActionMailer::Base.smtp_settings = {
        :address              => "smtp.gmail.com",
        :port                 => 587,
        :domain               => "gmail.com",
        :authentication       => :plain,
        :user_name            => ENV.fetch('GOOGLE_EMAIL'),
        :password             => ENV.fetch('GOOGLE_EMAIL_PASSWORD'),
    }

  end

  task deliver: [:configure] do
    csv = CSV.read('recipients.csv', headers: true)
    progressbar = ProgressBar.create(total: csv.size)
    csv.each do |credentials|
      RakeMailer.lesson_plan(credentials.fetch('email')).deliver
      progressbar.increment
    end
  end
end